### ISSUE TITLE
[Epic] Set strategy for Instruqt Labs for community

### ISSUE THREAD

**Issue by samccann** [ansible-community/community-team#144]
This EPIC aims to track the work around Instruqt labs.

Those labs are easy ways for not expert folks to have a sandbox to play with directly from their browser without to have to install / download anything locally.

We need to clarify what is it we want to do with them.

Are they used ? Do we have metrics ?
What labs should be created / updated to match community expectation ?
Socialized it more that those labs exists (Bullhorn) to ensure people are aware of those

**Comment by samccann** [comment]
- [ ] Get community people to try out existing Insruqt lab and give feedback.
- [ ] Review https://www.redhat.com/en/interactive-labs/ansible and https://www.ansible.com/products/ansible-community-training
- [ ] Draft a strategy document for what's there, what's missing, and what needs to be fixed
- [ ] How far do we extend this to other ansible projects

**Comment by leogallego** [comment]
Regarding the "review interactive-labs[1] and ansible-community-training[2]" task, here is a summary:

Currently, the first[1] one is based on labs related to *using* AAP/Ansible, the second[2] one (community) is on *contributing*.

The current Community labs on Instruqt are as follow:

* Ansible Community - Creating your own Collection
* Ansible Community - Testing a Pull Request Locally
* Ansible Community - Developing an Ansible Module
* Ansible Community - Fixing a Bug
* Ansible Community - Adding Integration Tests to Ansible Collections
* Coming Soon 

I already got access to the repos and instruqt and I will be getting the current labs into the ansible/instruqt repo asap.
I will be getting my input into the gdocs later as well.

[1] https://www.redhat.com/en/interactive-labs/ansible 
[2] https://www.ansible.com/products/ansible-community-training

**Comment by samccann** [comment]
@leogallego these are all contributor-focused. Do we see a place for 'how to write playbooks' etc in this mix?

**Comment by samccann** [comment]
@leogallego @anweshadas this epic lacks a set of subissues that we can track progress on other than what I created in 
https://github.com/ansible-community/community-team/issues/144#issuecomment-1448294350

Can we finalize a checklist for how we will proceed here and then I can create subissues based on that checklist.

**Comment by leogallego** [comment]
Hi @samccann 

> @leogallego these are all contributor-focused. Do we see a place for 'how to write playbooks' etc in this mix?

Sorry the delay on this one. I'm still figuring out how to handle all our channels.
Currently most of the "how to use Ansible" are on the AAP labs. I would rather start by getting to work on the contributor labs first, but I have that down to discuss and agree on something to avoid effort duplication.



> @leogallego @anweshadas this epic lacks a set of subissues that we can track progress on other than what I created in [#144 (comment)](https://github.com/ansible-community/community-team/issues/144#issuecomment-1448294350)
> 
> Can we finalize a checklist for how we will proceed here and then I can create subissues based on that checklist.

I can add a few of what I have already done and what is missing while we discuss with @anweshadas the rest. Do you want me to go ahead and edit the issue with the current list and create the subissues?

**Comment by samccann** [comment]
@leogallego if you want to discuss the checkist with folks first, that's fine. if the checklist is in the description, then GitHub gives and easy one-click to turn each one into an issue.

**Comment by samccann** [comment]
@leogallego - any updates on this?

**Comment by leogallego** [comment]
HI @samccann, yes, I'm working on an internal doc as draft, but I can put some of that info here for ref:

This is a summary of the WIP plan:

- [x] Import the current Instruqt community labs tracks into the ansible/instruqt repo, DONE
- [x] Review the state of each available community lab from 2021, IN PROGRESS
- [ ] Update or remove the labs from community landing depending on above outcome, ON HOLD.
- [x] Evaluate and cross-post useful labs suitable for community from aap landing, IN PROGRESS
- [x] Enable and promote the labs for Contributor Summit, Ansible Community Days or other events, IN PROGRESS
- [x] Enable and promote the labs for the Meetup Organizer Toolkit, IN PROGRESS
- [ ] Enable and promote the labs for the Student Outreach initiatives, ON HOLD.
- [ ] Enable RH TAMs and Services to utilize the labs to promote contribution to Ansible project, ON HOLD.

I have the stats for the current offering in the community labs, the most popualar lab (creating your collection) has usually under 5 people per day (and only about 2 of those finish the lab if they do). The rest are even lower. 

For "Ansible Community - Creating your own Collection", I have the following comments:

1. About 2 min launch, which is long for the tasks it has.
2. There are 5 challenges, no replay or skip
3. No intro slides or texts to help what the lab is about and to guide from chapter to chapter
4. Talks about ansible-core 2.10 (which was base btw)
5. Uses ansible-core 2.11.4 / 2.11.12
6. Shows a deprecation warning due to Python 3.8 req for ansible-core 2.12: 
```
[DEPRECATION WARNING]: Ansible will require Python 3.8 or newer on the controller starting with Ansible 2.12. Current version: 3.6.8 (default, Jan 19 2022, 23:28:49) [GCC 8.5.0 20210514 (Red Hat 8.5.0-7)]. This feature will be removed from ansible-core in version 2.12.
/home/devops/.local/lib/python3.6/site-packages/ansible/parsing/vault/__init__.py:44: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography will remove support for Python 3.6 from cryptography.exceptions import InvalidSignature
```
7. Asks to copy a module named timezone.py into the plugins/modules. No actual development of plugin.
8. No roles and their relationship with collections are mentioned.
9. The final chapter, asks us to create a Playbook that sets the timezone, using both methods of calling the collection (FQCN and by "importing" it)

**Comment by samccann** [comment]
Thanks @leogallego this is great.  For the collections one - is it possible to 'open it up' for community to contribute and bring it up to more recent releases etc?

**Comment by samccann** [comment]
Status -  Goal is to have a few Getting started labs available for meetups - playbooks, awx, builder, navigator, and eda. Today a meetup organizer has to request the labs. Working on  **Writing your first playbooks** and **AWX** invites  for Sept.

**Comment by samccann** [comment]
Closing this out as the strategy is set. The deliverables are still being worked on separately.
