### ISSUE TITLE
[Epic] Reduce fragmentation

### ISSUE THREAD

**Issue by samccann** [ansible-community/community-team#159]
In an effort to reduce fragmentation across our Ansible projects ecosystem - 

- [x] [Create an overarching strategy for 2023](https://ansible.github.io/community/posts/ansible_community_strategy_2023.html)
- [x] [Share with the community and gather feedback](https://github.com/ansible-community/community-topics/issues/202)
- [x] Update the strategy and set is as done (potentially an ADR?)
- [x] Implement the forum

**Comment by samccann** [comment]
@GregSutcliffe - Does 'create a forum' have any subissues we should create to track progress on getting discourse up and running?

**Comment by GregSutcliffe** [comment]
Indeed it does. I'll break it down a bit once I get back :)
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by samccann** [comment]
Once the forum is up, we need likely to:

Needs to be ready by soft launch:
- [x] define the structure
- [x] set up initial admins/rights
- [x] promotion/communications plan to familiarize community with this (@cybette)

After soft launch:
- [x] Improve the styling/theme

**Comment by GregSutcliffe** [comment]
We also need the CNAME record (ticket opened with IT). That's the bare minimum, after that we need to look into the onboarding process for each part of the forum:


**Users**
- [ ]   - How to encourage use of the forum? Can we soft-deprecate `ansible-project` or do we need to look at migrating that sooner rather than later?
- [ ]   - Get people to answer - we can reach out to existing helpers in chat/list/stackoverflow to help, I think
- [ ]   - Marking questions as solved - likely need mods to do this until people get the idea

**Developers**
- [x]   - Need to work with Shane to get the Proposals / ADR working. Probably Jill too.
- [x]   - Onboard AWX first as an exemplar. Edge is probably going to be fast too
- [x]   - Mailing list imports (need to speak to CDCK)

**Events**
- [x]   - Calendar setup & website integration
- [x]   - Permissions to create events
- [ ]   - ICS links if we can get them (I've asked)
- [x] - Steering Committee private area?
- [x] - Many, many groups to create

Much of this can be done in parallel, and I'll gladly take help getting it done ;)

**Comment by samccann** [comment]
Do we also need to recruit those early mods? or will it start with the community team and Steering Committee members and grow from there based on discourse trust levels etc?

**Comment by samccann** [comment]
- AWX migration

**Comment by GregSutcliffe** [comment]
> Do we also need to recruit those early mods? or will it start with the community team and Steering Committee members and grow from there based on discourse trust levels etc?

I never replied to this, but for the record, it's the latter. We'll need to pick up the tab for a month or 3, but during that time Discourse's Trust Level system will ensure that frequent committed users will earn the right to fix many things (tags, topic titles, categorisation, etc) without us needing to manually vet them. We can design a process for moderators (and eventually admins I hope) a little later.

**Comment by samccann** [comment]
@GregSutcliffe - any update on the checklist here? Are we calling this forum epic done (as in launched and we're happy). The rest seem to be how to grow/expand over time (and we may want separate issues for onboarding other projects besides AWX over time...)

**Comment by samccann** [comment]
Based on discussions, AWX has closed their mailing lists in favor of the forum so that was our definition of 'done' for this epic. All other items can be handled as separate issues as needed.
