### ISSUE TITLE
[Epic] move most community eng tasks upstream

### ISSUE THREAD

**Issue by samccann** [ansible-community/community-team#160]
Currently in some areas like release (ansible-core and ansible community package) as well as building and publishing documentation, the community can not help or own those area as there is an hard dependency on being in Red Hat VPN to be able to trigger the Jenkins jobs.

The goal of this EPIC is to move all the things the community engineering team does that requires VPN access to a fully upstream only process where any community member could participate if they want, are willing to and trust worthy,

- [x]  audit what - in the process of releasing ansible community package - requires VPN, why and how we could bring that completely upstream/public
- [x]  audit what - in the process of releasing ansible-core - requires VPN, why and how we could bring that completely upstream / public
- [x] [Opening up Ansible Community package release  for the community](https://github.com/ansible-community/community-team/issues/307)
- [x] #497
- [x] open up core release build so community can build it.

**Comment by samccann** [comment]
After talking with the core team, we agreed to move the release pipeline of ansible-core from the internal team + VPN to a Github Action triggered whenever a new tag is created. This will completely make the release process of ansible-core live upstream and proper permission could be given to who we want to allow to create tags.

**Comment by samccann** [comment]
@anweshadas @oraNod - Is the checklist accurate? If so, I can turn them into subissues so we can track each one separately etc.

also, if any of the checklist items are done, please mark them done here so we know the status...thanks!

**Comment by oraNod** [comment]
@samccann I think maybe we should break opening up the package docs to community as a separate epic. I think @anweshadas is done with the package build side so if she can tick the other checkboxes then breaking the docs build into a separate thing means we can close this.

**Comment by samccann** [comment]
@anweshadas - are we at the point where the community package could be built by someone else? ...and if so, do we want to ask for a release manager for Ansible 8 or is that too soon?

**Comment by anweshadas** [comment]
Proposing it for Ansible 8 will be too soon.

**Comment by samccann** [comment]
Ok thanks for the clarification!
