### ISSUE TITLE
[Epic] Define the Ansible Community Strong Mission Statement

### ISSUE THREAD

**Issue by Andersson007** [ansible-community/community-team#187]
The new community website should accommodate a Strong mission statement somewhere as its slogan.

The current plan to come up with a mission statement (feel free to raise concerns/suggest improvements):
- [x] I’ll create a draft of a community topic that will contain a call to the community for help with defining the community mission statement. UPDATED: done https://hackmd.io/cNNjpT-AT_eCa4Vm5SXWKg
- [x] UPDATE: the [vote](https://discourse.ansible.im/t/ansible-community-strong-mission-statement/82/27?u=andersson007) to choose a placeholder in underway
- [x] Count votes, determine the placeholder: [Done](https://discourse.ansible.im/t/ansible-community-strong-mission-statement/82/30?u=andersson007) "Automation powered by people"
- [x] Incorporate the placeholder to the new website: Done, added to [MVP hackmd](https://hackmd.io/PAiBqUSnSFaAt9w2UUPngg?view)

Later:
- [x] Poll the community via a proper survey. The [draft](https://hackmd.io/cNNjpT-AT_eCa4Vm5SXWKg) and the below can be used

UPDATE: the below can be used later when conducting the survey
- [x] Our team will review the draft.
- [x] Publishing the draft as the [community topic](https://github.com/ansible-community/[community-topics](https://github.com/ansible-community/community-topics/issues)/issues) calling for feedback via Bullhorn / Community meeting, etc, in Social room.
- [x] [The topic](https://forum.ansible.com/t/ansible-mission-statement-brainstorming-time/176) has been created based on the survey results.
- [x] Collecting feedback in the [topic](https://forum.ansible.com/t/ansible-mission-statement-brainstorming-time/176). 
- [x] outreach core/champions personally (from this point, the steps were discussed and agreed withing the team on Matrix):
- [x] inform champions about the topic, give them a week to respond
- [x] open a separate topic next Monday after the champions meeting with the poll
- [x] invite people to approve/choose in Bullhorn
- [ ] invite people in channels (including SC)
- [x] close the poll
- [x] announce in Bullhorn
- [x] Incorporating the Strong mission statement to the new website.

**Comment by Andersson007** [comment]
to go or not to go further, waiting for team's feedback on https://discourse.ansible.im/t/ansible-community-strong-mission-statement/82/21?u=andersson007

**Comment by Andersson007** [comment]
It seems that the majority of the team is for defining the mission statement later through a survey or something (there's not enough time for that at the moment).
I've opened a [vote](https://discourse.ansible.im/t/ansible-community-strong-mission-statement/82/27?u=andersson007) to choose a placeholder for the new website from existing slogans. It ends on 2023-04-03

**Comment by samccann** [comment]
@Andersson007 Great checklists here! Should I turn them into subissues so we can track them in our project board for April/May timeframes individually?

**Comment by Andersson007** [comment]
> @Andersson007 Great checklists here! Should I turn them into subissues so we can track them in our project board for April/May timeframes individually?

@samccann i think the upper two (Count votes.., Incorporate..) can be turned into issue. So yes, please.
The rest is not determined yet. It'll get clearer after the summit.

**Comment by Andersson007** [comment]
- The poll is [done](https://discourse.ansible.im/t/ansible-community-strong-mission-statement/82/30?u=andersson007).
- `Automation powered by people` has been added to the [MVP hackmd](https://hackmd.io/PAiBqUSnSFaAt9w2UUPngg?view)
- This task description has been updated correspondingly

**Comment by samccann** [comment]
@Andersson007 - where are we on this one? I know we have the survey but not sure when it ends?

**Comment by Andersson007** [comment]
@samccann yep, i remember about it, thanks
~~BTW yesterday, after reading up about the topic, i found out that we are actually trying to define our **slogan** here, not a mission statement and they are not nearly the same thing despite possible intersections in wording.
It's also OK as having a slogan is a good and important thing, though we need to work a bit more on this. I'll try to elaborate on that this week~~

Let's analyze feedback. Pinged Greg about that

**Comment by Andersson007** [comment]
[The forum topic](https://forum.ansible.com/t/ansible-mission-statement-brainstorming-time/176) has been created.
Put mine option.
Collecting more feedback.

**Comment by Andersson007** [comment]
@GregSutcliffe @cybette 
I suggest collecting the Mission statement options in the [post](https://forum.ansible.com/t/ansible-mission-statement-brainstorming-time/176) this week, then summarize options and ~~open a vote~~ after the official forum launch.
What do you think?

**Comment by cybette** [comment]
As we've discussed let's gather feedback over the next few weeks (@GregSutcliffe will mention it in Bullhorn this week), however we will use the feedback to shape the statement instead of putting it through a vote. 

Great progress on this, really excited to see how it'll turn out :)

**Comment by Andersson007** [comment]
As the next step we agreed on Matrix on is:
@Spredzy is going to reach out to champions and other folks;
@GregSutcliffe iirc was also going to reach out to someone, though i'm not 100% sure:)

**Comment by Andersson007** [comment]
@GregSutcliffe if you remember could you please remind me what we agreed on in our last 1:1 on https://forum.ansible.com/t/ansible-mission-statement-brainstorming-time/176 ?

If I'm not wrong, it was about:
1. Waiting until Galaxy things calm down.
2. Splitting https://forum.ansible.com/t/ansible-mission-statement-brainstorming-time/176 into 2 topics:
  - Mission statement (which is not as complicated)
  - Slogan.
3. Then we'll proceed with `Mission statement` first. There will be no vote but just maybe asking if people are OK in a dedicated topic.
4.  Then we'll proceed with `Slogan` topic.

Questions:
- Are there anything to add / correct?
- I don't see any objections on the [Mission statement wording](https://forum.ansible.com/t/ansible-mission-statement-brainstorming-time/176#our-mission-2). Should we even distract the community with it? Instead, can we just use it on the new site and the forum without broader community discussions? Moreover, it's not something like a slogan and can be changed any time later (which i wouldn't expect a need for).
- For how long should we wait until we consider things with Galaxy calmed down? Would be December 1st fine to open the broadly advertised Mission statement feedback topic?

**Comment by GregSutcliffe** [comment]
The steps are right, I recall the same discussion. I'm meeting with Galaxy tomorrow to find work out what else we can do to explain things to the community, so I'll have a clearer idea after that, but I would expect Dec 1st *at the latest* and we'll see if we can go earlier.

I agree we've not had much feedback on the wording, but the forum was new and few people saw it. Perhaps we should pin it for a bit in the project list? Or even a global pin? What do others think here?

**Comment by Andersson007** [comment]
@GregSutcliffe let me create a separate Mission statement (w/o the Slogan) topic for the pin (so I'm OK with pinning it). What do you think?

**Comment by cybette** [comment]
+1 for pinned Mission statement topic

**Comment by Andersson007** [comment]
Created https://forum.ansible.com/t/define-our-community-mission-statement/2101

**Comment by Andersson007** [comment]
As per the [comment](https://github.com/ansible-community/community-team/issues/187#issuecomment-1786831393), closing the epic as complete https://forum.ansible.com/t/define-our-community-mission-statement/2101
For the slogan one, i'll create another issue.
Thanks everyone!
