### ISSUE TITLE
[Epic] archive old docs

### ISSUE THREAD

**Issue by samccann** [ansible-community/community-team#22]
EOL docs still get a lot of hits due to showing up in google search results. Investigate options on how to recover from this.

**Comment by samccann** [comment]
Work to date has included investigating ways to use HTTP_REFERER to create redirects to latest if the referrer is NOT docs.ansible.com, or not empty (aka not a bookmark).  The empty referrer redirect isn't working but notes are [here](https://hackmd.io/0B7n-FUySF6MB3CQeaqUkA).

**Comment by samccann** [comment]
Next approach is what was originally approved by RH search expert:

- [x] create a docs archive site (such as docs.ansible.com/archive/xxx)
- [x] - Publish EOL docs to archive site
- [x] - Add Archive Docs link to docs.ansible.com
- [x] - Add redirects from existing EOL docs to latest
- [x] - Announce this change.

**Comment by samccann** [comment]
Test published 2.3 to http://docs.testing.ansible.com/archive/ansible/2.3/

**Comment by samccann** [comment]
Archive site set up - https://docs.ansible.com/ansible-prior-versions.html
2.3 archived but redirects not in place yet.

**Comment by samccann** [comment]
Redirects are now in place. We'll wait a week or so in case there are other problems, if not, the process going foward is to archive and add redirects for the following releases:

- [x] 2.4
- [x] 2.5
- [x] 2.6
- [x] 2.7
- [ ] 2.8

2.9 is not EOL from the Red Hat perspective. Even when it does go EOL, we should probably wait an extra year as that is last pre-collection release and users are lingering on it.

After that, we need to decide if we archive core releases or not (2.10, 2.11). They do not get as much website traffic so we may not need to, unless we feel it's important that all EOL docs evenutally live at docs.ansible.com/archive.

Similarly, Ansible release docsites exist for 3,4,5,6, but users seldom access via the numbered urls. Most traffic goes to /latest/.

Adobe analytics shows that these older releases (2.10, 2.11, Ansible 3, 4, 5, and 6) account for less than 0.04% of monthly traffic.
