### ISSUE TITLE
[epic] Create Common community documentation site

### ISSUE THREAD

**Issue by samccann** [ansible-community/community-team#237]
In order to simplify contributions and provide a common home for all Ansible community projects, investigate and implement a strategy to bring these sites together.

**Comment by samccann** [comment]
Two main efforts currently happening here:

- [x] moving ansible rst docs to a new repo
- [x] publishing all ecosystem docs to Read the Docs
- [x] https://github.com/ansible/docsite/issues/215. 
- [ ] https://github.com/ansible/docsite/issues/216

Each of these has many moving parts (so are like sub-epics on their own).

**Comment by samccann** [comment]
@oraNod - the last two items on the checklist above don't have actual issues yet. Should I these issues in the ansible/docsite repo and link them here?  

I'm trying to ensure every epic has one subissue that is actively being worked on so doesn't necessarily matter where the issues are, so long as they are linked here.

**Comment by oraNod** [comment]
@samccann Sounds fine to me, thanks.
