### ISSUE TITLE
[epic] Rewards and Recognition

### ISSUE THREAD

**Issue by samccann** [ansible-community/community-team#302]
This epic contains the steps we'll take to spin up a rewards and recognition program for the Ansible community. 

NOTE: The initial steps here depend on the forum launch. Some may eventually tie to the website launch as well.

- [ ] [Create community shout-out zone](https://github.com/ansible-community/community-team/issues/192)
- [ ] [ rewards and recognition for meetup organizers and event swag](https://github.com/ansible-community/community-team/issues/194)
```[tasklist]
### Tasks
- [ ] https://github.com/ansible-community/community-team/issues/312
```

**Comment by samccann** [comment]
need to figure out the discourse badging and if/how we can integrate with other badging ideas (for github/meetups etc).

**Comment by cybette** [comment]
Repo for Ansible badges: https://github.com/ansible-community/ansible-badges
Ansible Community Badgr: https://badgr.com/public/issuers/LxI9xTZ5Qee4Luk5biGKWg/badges

People are currently still requesting the meetup badges since we've started giving them out last year, [example](https://badgr.com/public/assertions/CPBsH6-TRwqCpYSnZnPUmw).

**Comment by samccann** [comment]
Started [user of the week shoutout](https://forum.ansible.com/t/user-of-the-week/806/1) on the forum
Manually assigning badges.
