### ISSUE TITLE
[Epic] Move ansible/ansible rst documentation to ansible/ansible-documentation repo

### ISSUE THREAD

**Issue by samccann** [ansible-community/community-team#306]

**Comment by samccann** [comment]
aka docs lift and shift. Most of this is done but forgot to create a tracking epic for it all.

- [x] Coordinate with community to review and approve the plan
- [x] clone /docs and /examples dirs to new repo
- [x] Set up repo and CI
- [x] Update jenkins jobs for new repo
- [x] Test and evaluate with community
- [x] three week -trial period - publishing from new repo
- [x] Final DaWGs approval
- [x] Remove /docs and /examples from ansible/ansible.
- [x] Post-launch cleanup tasks

**Comment by samccann** [comment]
details and final tasks at https://hackmd.io/c9SEj2FaRvKF5UhXNl9NtA

**Comment by samccann** [comment]
Calling this done!
