### ISSUE TITLE
[Task] Cross-project contributor experience: create README template

### ISSUE THREAD

**Issue by Andersson007** [ansible-community/community-team#420]
Cross-project contributor experience: create README template in the [project_template](https://github.com/ansible-community/project-template) repository

A sub-task of https://github.com/ansible-community/community-team/issues/416

PRs:
- [x] https://github.com/ansible-community/project-template/pull/5
- [x] https://github.com/ansible-community/project-template/pull/6
- [x] https://github.com/ansible-community/project-template/pull/7
