### ISSUE TITLE
[Epic] Migrate Ansible community docs hosting to ReadTheDocs

### ISSUE THREAD

**Issue by samccann** [ansible-community/community-team#497]
## Background

The Ansible community team has been working to open up docs publishing to trusted community members with the intent to make the process transparent to the wider community and to increase ownership. We have organized projects under the `ansible` namespace on ReadTheDocs at: https://ansible.readthedocs.io/en/latest/

In CY 2023, all RH-managed Ansible projects hosting content on ReadTheDocs was moved under the `ansible` namespace. The goal of this epic is to migrate the package docs and core docs that are hosted on RH infrastructure to ReadTheDocs.

- Package docs are currently available at: https://docs.ansible.com/ansible/latest/index.html
- Core docs are currently available at: https://docs.ansible.com/ansible-core/devel/index.html

## User stories and tasks

- [x] https://github.com/ansible-community/community-team/issues/514
- [x] #522
- [x] #541
- [x] #542
- [ ] As a member of the Ansible community, I want to be aware of this migration, provide input on it, and collaborate on the implementation where possible.
- [ ] As a member of the Ansible community, I want to ensure that I can still access technical content at the `docs.ansible.com` subdomain.
- [ ] As a member of the core team, I need a clear understanding of the strategy for the docs migration.
- [ ] As a member of the core team, I want to publish ansible-core documentation on Read The Docs alongside the rest of the projects.

## Related details

- https://hackmd.io/Ejh1G6hjSO2DFiJXyUpUsw?view
- https://hackmd.io/c9SEj2FaRvKF5UhXNl9NtA?view

## Definition of done

This work is completed after all user stories and related sub-tasks are complete. Additionally the epic is done when Ansible community members can actively participate in the docs publishing process and access technical content from `docs.ansible.com` that is hosted on ReadTheDocs.

**Comment by oraNod** [comment]
This follows up on https://github.com/ansible/docsite/issues/179
