### ISSUE TITLE
[Sub-task] Optimize the inclusion requirements

### ISSUE THREAD

**Issue by Andersson007** [ansible-community/community-team#502]
Story sub-task of https://github.com/ansible-community/community-team/issues/499

**Comment by Andersson007** [comment]
- [x] Started a PR https://github.com/ansible/ansible-documentation/pull/1422
- [x] Started a PR dependent on ^ https://github.com/ansible-collections/overview/pull/235
- [x] Open a forum topic

**Comment by Andersson007** [comment]
there were several other PR not reflected here. closing as the main one is being under voting
