### ISSUE TITLE
[Sub-task] Define a list of repos that can be potentially archived, discuss, put a list here, create a sub-task per repo

### ISSUE THREAD

**Issue by Andersson007** [ansible-community/community-team#509]
Sub-task of story https://github.com/ansible-community/community-team/issues/507

**Comment by Andersson007** [comment]
These repos should be archived and it'll really reduce the fragmentation by moving the activities to the forum.
- [ ] https://github.com/ansible-collections/ansible-inclusion
- [ ] https://github.com/ansible-community/community-topics
- [ ] https://github.com/ansible-collections/overview


The following repos will not affect fragmentation noticeably as most of them are inactive anyway but can be closed along the way

Possible:
- Docs temporary repos when we were moving stuff from ansible/ansible (ping Don)
- https://github.com/ansible-collections/.github
- https://github.com/ansible-collections/news-for-maintainers
- https://github.com/ansible-community/presentations
- https://github.com/ansible/blog
- https://github.com/ansible/ansible-on-clouds-dev-docs

Relevant?

- https://github.com/ansible-community/pytest-testinfra
- https://github.com/ansible-community/role2collection
- https://github.com/ansible-community/hebbot
- https://github.com/ansible-community/rss-feed-aggregator-template
- https://github.com/ansible-community/go-luigi
- https://github.com/ansible-community/operator-sdk-performance-testing
- https://github.com/ansible-community/sphinx-ansible
- https://github.com/ansible-community/ppa
- https://github.com/ansible-community/ansible.content_builder-1
- https://github.com/ansible-community/ansible.content_builder-2
- https://github.com/ansible-community/ansible-role-boundary
- https://github.com/ansible-community/protogen
- https://github.com/ansible-community/ansible-test-gh-workflow
- https://github.com/ansible-community/collection-explorer
- https://github.com/ansible-community/ara-collection: should be move to the ansible-collections org?
- https://github.com/ansible-community/community.yang
- https://github.com/ansible-community/collection-explorer
- https://github.com/ansible-collections/ansible.drill
- https://github.com/ansible-collections/symantec.epm
- https://github.com/ansible/ansible-examples

Stats repos:
- https://github.com/ansible-community/stats-data
- https://github.com/ansible-community/stats-collections
- https://github.com/ansible-community/stats-map

Meetup repos (many of them are even empty):
- https://github.com/ansible-community/ansible-minneapolis-meetup
- https://github.com/ansible-community/ansible-stl-meetup
- https://github.com/ansible-community/ansible-richmond-meetup
- https://github.com/ansible-community/ansible-vancouver-bc-meetup
- https://github.com/ansible-community/ansible-seattle-meetup
- https://github.com/ansible-community/ansible-losangeles-meetup
- https://github.com/ansible-community/ansible-zurich-meetup
- https://github.com/ansible-community/Ansible-pune-meetup
- https://github.com/ansible-community/ansible-dresden-meetup
- https://github.com/ansible-community/ansible-benelux-meetup
- https://github.com/ansible-community/ansible-hamburg-meetup
- https://github.com/ansible-community/ansible-munich-meetup
- https://github.com/ansible-community/ansible-kolkata-meetup
- https://github.com/ansible-community/ansible-buenosaires-meetup
- https://github.com/ansible-community/ansible-london-meetup


I've archived on the spot:
- [x] https://github.com/ansible-community/instruqt-scenarios
- [x] https://github.com/ansible-collections/community.storage

**Comment by Andersson007** [comment]
@oraNod @samccann are there any doc unused repos we could add in the list? (feel free to edit the comment ^)

I also ask you all including @anweshadas about archiving all the meetup repos? maybe of them are empty and even if not is there any value in having them visible? How about just archiving all of them?

@GregSutcliffe can something from stats repos above be archived?

About the rest, I suggest opening an issue maybe + a PR against READMEs saying "This repo has been archived. If you think it shouldn't have been, please contact <out team email>". Thoughts?

**Comment by oraNod** [comment]
@Andersson007 Do we want to consider repos under `ansible-community` only? Or are there repos under `ansible` that we could include as part of the archive effort? Such as https://github.com/ansible/ansible-on-clouds-dev-docs

**Comment by Andersson007** [comment]
> @Andersson007 Do we want to consider repos under `ansible-community` only? Or are there repos under `ansible` that we could include as part of the archive effort? Such as https://github.com/ansible/ansible-on-clouds-dev-docs

@oraNod if you know some inactive ones across all the orgs, we could try to archive them too, why not, but not investing to much time and effort as the primarily epic focus is repos that are actively used now like those 3 at the top.
As there's not as many repos in ansible-community and ansible-collections, i went through all and it wasn't take a lot of time. Can be more challenging for the ansible org:)

**Comment by samccann** [comment]
I would also ping @cybette on those meetup repos. I don't know their original purpose but perhaps the forum is a better place for them now anyway?

As for other items to archive - https://github.com/ansible/ansible-examples is a candidate for sure. It will take a bit longer to do, as there are multiple open issues and prs to comment on to say the archive is unmaintained etc, and its pointed to from the docs so we'd have to remove them as well.  

It's not a fragmentation issue though so maybe we just open an issue in our team org to ensure we take care of it at some point.

**Comment by oraNod** [comment]
@Andersson007 I added five repos under the "Possible" section. Those seem like potential candidates to me. Not sure of any others.

**Comment by Andersson007** [comment]
thanks everyone!
Opened a [forum topic](https://forum.ansible.com/t/reduce-fragmentation-moving-stuff-to-the-forum-and-archiving-repos/5141), let's wait a bit and proceed next week

**Comment by cybette** [comment]
For the meetup repos, I know a few meetup groups have been using them to store and share slides/code/other content from their events. London meetup group uses the github issues for proposing and accepting talks - @gundalow is this still the case?

The forum can be useful for discussing talk proposals, but afaik there's no easy way to upload attachments for sharing. Or I think there's an option that can be enabled - @GregSutcliffe will know more.

If we are to archive the meetup repos, for those that have no activities since creation, I think they can be archived safely. Although @leogallego created the [Buenos Aires](https://github.com/ansible-community/ansible-buenosaires-meetup) one fairly recently - maybe he has some plans for it?

For those that have content from past meetups, if we decide to move all new meetup activities to the forum, the admins/contributors to those repos should be notified and given enough time to arrange how they want their content to be organized (e.g. they may keep the old content archived on GitHub but still accessible (read only), or move everything the forum), and provided an easy process to do so.

**Comment by samccann** [comment]
I archived most of the inactive meetup repos. The 3-4 that has some activity I posted a general issue asking if we should keep the repo alive or have some other place to share presentations. We already have the https://github.com/ansible-community/presentations where the community team shares presentations.

**Comment by samccann** [comment]
@oraNod - the https://github.com/ansible/ansible-on-clouds-dev-docs goesn't seem to exist and I can't find an equivalent.  Also there's a note to ask you about `Docs temporary repos when we were moving stuff from ansible/ansible` ?
