### ISSUE TITLE
[Task]: DevConf 2024: Introduction to creating automation with Ansible Development Tools

### ISSUE THREAD

**Issue by oraNod** [ansible-community/community-team#544]
https://pretalx.com/devconf-cz-2024/talk/STVCWC/

```[tasklist]
### Tasks
- [x] Evaluate InstructLab materials
- [x] Provide feedback to Leo and Anshul
- [x] Practice using DevTools based on workshop objectives
```
