### ISSUE TITLE
As a member of the Ansible community, core team, or other project team, I need to understand the strategy for the migration so that I am aware of the changes and can help prevent bad outcomes 

### ISSUE THREAD

**Issue by oraNod** [ansible-community/community-team#550]
This is a user story that is part of epic https://github.com/ansible-community/community-team/issues/497

```[tasklist]
### Tasks
- [ ] https://github.com/ansible-community/community-team/issues/549
- [ ] https://github.com/ansible-community/community-team/issues/541
- [ ] https://github.com/ansible-community/community-team/issues/542
```
