### ISSUE TITLE
As a member of the community engineering team, I need to ensure that docs hosted on Read The Docs is easy to discover, navigate, and consistent with the current experience

### ISSUE THREAD

**Issue by oraNod** [ansible-community/community-team#551]
This is a user story that is part of epic https://github.com/ansible-community/community-team/issues/497

```[tasklist]
### Tasks
- [ ] https://github.com/ansible-community/community-team/issues/546
- [ ] https://github.com/ansible-community/community-team/issues/547
- [ ] https://github.com/ansible-community/community-team/issues/548
- [ ] https://github.com/ansible-community/community-team/issues/552
```
